// <auto-generated />
using System;
using AutoFeedSiqi.Models.CommonComponents.EntityTypeConfiguration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoFeedSiqi.Migrations
{
    [DbContext(typeof(AutoFeedSiqiDbContext))]
    partial class AutoFeedSiqiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("AutoFeedSiqi.Models.CommonComponents.Model.Configuration", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AutoDataPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("auto_data_path");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_at");

                    b.Property<string>("ExcelPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("excel_path");

                    b.Property<bool>("Invisible")
                        .HasColumnType("INTEGER")
                        .HasColumnName("invisible");

                    b.Property<string>("IskyEmail")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("isky_email");

                    b.Property<string>("IskyHost")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("isky_host");

                    b.Property<string>("IskyPassword")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("isky_password");

                    b.Property<string>("IskyToken")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("isky_token");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_updated_at");

                    b.Property<string>("QbHost")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("qb_host");

                    b.Property<string>("QbPassword")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("qb_password");

                    b.Property<string>("QbTags")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("qb_tags");

                    b.Property<string>("QbUserName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("qb_user_name");

                    b.Property<string>("SiqiCookie")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("siqi_cookie");

                    b.Property<string>("SiqiHost")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("siqi_host");

                    b.Property<string>("SiqiPasskey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("siqi_passkey");

                    b.Property<string>("SiqiTrack")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("siqi_track");

                    b.Property<string>("SiqiUploaderToken")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("siqi_uploader_token");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("token");

                    b.HasKey("Id")
                        .HasName("pk_configurations");

                    b.ToTable("configurations", (string)null);
                });

            modelBuilder.Entity("AutoFeedSiqi.Models.CommonComponents.Model.Feed", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id")
                        .HasComment("Id");

                    b.Property<string>("Authors")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("authors")
                        .HasComment("作者");

                    b.Property<int>("Color")
                        .HasColumnType("INTEGER")
                        .HasColumnName("color")
                        .HasComment("颜色：黑白、全彩、混合等等");

                    b.Property<int>("Condition")
                        .HasColumnType("INTEGER")
                        .HasColumnName("condition")
                        .HasComment("状态：单本完、部分、合集完、精选集、丛书等等");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_at")
                        .HasComment("创建时间");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date")
                        .HasComment("出版日期");

                    b.Property<int>("DoubanId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("douban_id")
                        .HasComment("豆瓣Id");

                    b.Property<int>("Extension")
                        .HasColumnType("INTEGER")
                        .HasColumnName("extension")
                        .HasComment("格式：pdf、mobi等等");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT")
                        .HasColumnName("isbn")
                        .HasComment("ISBN");

                    b.Property<int>("Language")
                        .HasColumnType("INTEGER")
                        .HasColumnName("language")
                        .HasComment("语言：中简、中繁、英语等等");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_updated_at")
                        .HasComment("最后更新时间");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("path")
                        .HasComment("ID对应的文件目录");

                    b.Property<string>("Press")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("press")
                        .HasComment("出版社");

                    b.Property<string>("PreviewUrl")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("preview_url")
                        .HasComment("预览图url，用分号分割");

                    b.Property<int>("Quality")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quality")
                        .HasComment("品质：一般质量、高质量、超高质量等");

                    b.Property<uint>("SiqiId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("siqi_id")
                        .HasComment("思齐Id");

                    b.Property<int>("Sort")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort")
                        .HasComment("类别：历史传记、人文艺术、科普科技等等");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source")
                        .HasComment("来源：自制、个人收集、自购、转载等等");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("summary")
                        .HasComment("内容简介");

                    b.Property<int>("Task")
                        .HasColumnType("INTEGER")
                        .HasColumnName("task")
                        .HasComment("ID对应的当前任务");

                    b.Property<bool>("TaskState")
                        .HasColumnType("INTEGER")
                        .HasColumnName("task_state")
                        .HasComment("ID对应的当前任务完成情况");

                    b.Property<int>("Team")
                        .HasColumnType("INTEGER")
                        .HasColumnName("team")
                        .HasComment("制作组：SQB，其他");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("title")
                        .HasComment("书名");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type")
                        .HasComment("类型：连环画、插图画、漫画等等");

                    b.HasKey("Id")
                        .HasName("pk_feeds");

                    b.ToTable("feeds", null, t =>
                        {
                            t.HasComment("思齐PT站的发种记录");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
